name: Build Dolt
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21 # Or latest supported
      - name: Install CGO dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libicu-dev
      - name: Build
        run: |
          cd go && CGO_ENABLED=1 go build -ldflags '-extldflags "-static"' -o dolt ./cmd/dolt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolt-binary
          path: go/dolt
